name: 'Checkout'
description: 'Checkout a Git repository at a particular version'
author: 'GitHub'
inputs:
  repository:
    description: 'Repository to checkout'
    required: false
    default: ${{ github.repository }}
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
    default: 'refs/heads/${{ github.ref }}'
  token:
    description: 'Authentication token used to fetch the repository'
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: 'node12'
  main: 'dist/index.js'
